### ISSUE TITLE
Working with NCAR HPC Systems 

### ISSUE THREAD

**Issue by philipc2** [philipc2/siparcs-project-13#13]
## Part 1: System Information

This summer, you will have access to two NCAR HPC systems: Casper and Derecho. Read the following documentation pages to familiarize yourself with the HPC environment. 

- [x] Read the [Derecho Supercomputer Documentation](https://arc.ucar.edu/knowledge_base/74317833)
- [x] Read the [Casper Cluster Documentation](https://arc.ucar.edu/knowledge_base/70549550)
- [x] Read the [Glade filesystem documentation](https://arc.ucar.edu/knowledge_base/68878466)

## Part 2: Python and Jupyterhub Setup

- [x] Read through the [Jupyterhub Documentation](https://arc.ucar.edu/knowledge_base/70549913)

After reading through the documentation, you should be all good to start using Jupyterhub. For this part, you can spin up a Casper Login node. 
```
mamba create -n intro-to-hpc
mamba activate intro-to-hpc
mamba install -c conda-forge numpy numba dask ipykernel
```

In your home directory, clone this repository and create a notebook called `intro-to-hpc.ipynb`. You can populate this notebook with whatever you'd like. However, try to import the packages that we installed above (i.e. `numpy`, `dask`, `numba`. Include this notebook in your branch and pull request.

### Connecting to Derecho

You can connect to a Derecho login node by running the following in your terminal or ssh client

```
ssh username@derecho.hpc.ucar.edu
````

Create a simple Python file called `print-cpu.py` that executes the following:

```Python
import os
print(f"Number of CPU Cores: {os.cpu_count()}")
```

Run this script on the login node. Document the printout in a markdown file named `part-3.md`

### Interactive Jobs

```
qsub -I -q main -A NVST0001 -l select=1:ncpus=64: -l job_priority=regular -l walltime=00:10:00
```

Run `print-cpu.py` on the node you were allocated. Document the printout in the same file as above.

### PBS Jobs
- [x] [Read the documentation for PBS Job Scripts ](https://ncar-hpc-docs.readthedocs.io/en/latest/pbs/job-scripts/)

Create a PBS bash script for executing `print-cpu.py` on a derecho node with 64 cpu cores. Document the printout in the same file as above and include the bash script as part of this pull request. 

## Part 4: Python Daxpy 

Inside the `intro-to-hpc` directory, you will find a Python script called `daxpy.py`. [Daxpy is one of the original subroutines from the BLAS package. ](https://daxpy.xyz/daxpy/)

This script contains five implementions of DAXPY
* `daxpy_list`: Basic Python implementation, iterating and appending results to a list 
* `daxpy_list_comp`: Uses Python List Comprehension
* `daxpy_numpy`: Vectorized Numpy implementation
* `daxpy_numba`: Basic Numba implementation
* `daxpy_dask`: Basic Dask implementation

The script can be run by running `python daxpy.py` with the following parameters
* `-n`: Vector size 
* `-m`: Method to run 

For example, if I wanted to run DAXPY using the numpy implementation with a vector size of 10000, I would run:
```
python daxpy.py -n 10000 -m daxpy_numpy
```

Using what you've learned so far, fill out the following tables and discuss any observations. 

Using a Derecho node with 128 cores, fill out the execution time for the following methods.

| Method / Vector Size               | 10,000     | 100,000    | 1,000,000  | 10,000,000 | 100,000,000 |
|--------------- | ---------- | ---------- | ---------- | -----------| ------------|
| Standard List |                 |                |                 |                 |                  |
| List Comp|     |                 |                |                 |                 |                  |
| Numpy          |                 |                |                 |                 |                  |
| Numba          |                 |                |                 |                 |                  |
| Dask              |                 |                |                 |                 |                  |

Using a fixed vector size of 100,000,000, fill out the following table. 

| Method / # CPU Cores              | 1     | 2    | 4  | 8 | 16 | 32 | 64 | 128
|--------------- | ---------- | ---------- | ---------- | -----------| ------------| ------------| ------------| ------------| 
| List Comp|     |                 |                |                 |                 |                  |                  |                  |                  |
| Numpy          |                 |                |                 |                 |                  |                  |                  |                  |
| Numba          |                 |                |                 |                 |                  |                  |                  |                  |
| Dask              |                 |                |                 |                 |                  |                  |                  |                  |

**Comment by philipc2** [comment]
```Python

module load conda
conda activate intro-to-hpc
python daxpy.py -n 10000 -m daxpy_numpy
```

**Comment by philipc2** [comment]
```
... batch stuff

echo "Standard List"
python daxpy.py -n 10000 -m list
python daxpy.py -n 100000 -m list
python daxpy.py -n 1000000 -m list
python daxpy.py -n 10000000 -m list
python daxpy.py -n 100000000 -m list

echo "List Comp"
python daxpy.py -n 10000 -m list_comp
python daxpy.py -n 100000 -m list_comp
python daxpy.py -n 1000000 -m list_comp
python daxpy.py -n 10000000 -m list_comp
python daxpy.py -n 100000000 -m list_comp

... repeat for all methods



OMP_NUM_THREADS=1
OMP_NUM_THREADS=2

```

**Comment by rytam2** [comment]
**Execution time on Derecho node with 128 cores** 

| Method / Vector Size | 10,000 | 100,000 | 1,000,000 | 10,000,000 | 100,000,000|
|-- | -- | -- | -- | -- | --|
|Standard List | 0.0007572174072265625  | 0.0074193477630615234  | 0.08117222785949707  |  0.7613668441772461| 7.5106658935546875 |  
|List Comp |  0.0007872581481933594 |  0.0076448917388916016 | 0.07628130912780762  | 0.7801737785339355 |  7.4977428913116455
|Numpy | 1.3113021850585938e-05  | 0.00017189979553222656  | 0.0019898414611816406  |  0.022642135620117188 |  0.2066667079925537|
|Numba |  4.536669731140137 | 0.28264760971069336  |  0.2836134433746338 |  0.29659104347229004 | 0.39729785919189453| 
|Dask |0.0009293556213378906| 0.0009152889251708984|0.0009112358093261719|0.0009217262268066406|0.0009229183197021484|

**Takeaways:**
- Numpy performs est when dealing with midsized vectors;
- Numba has the most drastic performance increase from 10,000 to 100,000 sized vectors; performance stay roughly the same for larger sizes 
- Dask uses roughly the same amount of resources regardless of vector size for daxpy calculations. Perhaps due to the same chunking?

**Comment by rytam2** [comment]
**Execution Time on Derecho for Fixed vector size of 100,000,000 with varying cores** 
| Method / # CPU Cores | 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128
| -- | -- | -- | -- | -- | -- | -- | -- | --
| List Comp | 7.161593437194824  |  7.242587566375732 | 7.152298212051392  | 7.233917713165283  |  7.210004806518555 | 7.180241107940674   | 7.17792820930481  |  7.181557893753052 | 
| Numpy |  0.2044975757598877 |  0.20385313034057617 |  0.2035682201385498 |  0.20505380630493164 |  0.20279598236083984 |  0.20670747756958008 | 0.20650768280029297  |  0.20790433883666992
| Numba | 3.9977023601531982  | 2.4777588844299316  | 7.1259002685546875  |  5.488278865814209|  2.1277427673339844 | 6.12350606918335  | 3.242428779602051  |  3.2532191276550293
| Dask | 0.0008993148803710938  |  0.00091552734375 |  0.0009202957153320312 | 0.0009508132934570312  |  0.0009195804595947266 | 0.0009050369262695312  |  0.0009217262268066406 | 0.0009334087371826172

**Observations:** 
- Consistent execution time for list_comp and numpy, with numpy significantly faster. No significant performance change across increasing cores. 
- Fluctuating performance time across increasing number of cores for Numba... Not sure why for such performance pattern - due to how the parallelization is carried out for Numba? 
- Very slight increase in execution time for Dask, but overall consistent execution time and remains the fastest performance time across all methods
